/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "bloomfilter_constants.h"



const bloomfilterConstants g_bloomfilter_constants;

bloomfilterConstants::bloomfilterConstants() {
}



