/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef bloomfilter_CONSTANTS_H
#define bloomfilter_CONSTANTS_H

#include "bloomfilter_types.h"



class bloomfilterConstants {
 public:
  bloomfilterConstants();

};

extern const bloomfilterConstants g_bloomfilter_constants;



#endif
