/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "DataService_constants.h"

namespace DataService {

const DataServiceConstants g_DataService_constants;

DataServiceConstants::DataServiceConstants() {
}

} // namespace

